apprise_notify_urls: ENC[AES256_GCM,data:TMtRMj3u3gbXdd8r0VCWDaGYCWIPjABktctXIJH2s1WmHyXCNFC4pJQ61qDbrYcO+6o8tnZmsHnGzXgqdgrNfqcbAV4vnp9MDSfybBcpwg6c/Pcp3IrhfDJhzKgIEdS8Ce1z,iv:ERWUrmqdtqjyxEC/eMJFtEpGTsgKv1gMlM0LycvTHjE=,tag:hb/lZzeCvKytfVQozg2B7g==,type:str]
admin_user_password_hash: ENC[AES256_GCM,data:oka5W75RmBSevg5QhgnZSScypQWuJWu/MEsoQcCYf51eFyGQpd5UeYz5NjcxfWC4t45/B8LmPdH+866sZ1OiauPk+1afLZxr+s/fU3mkLCBwPnQf5KfSG6iRK9LQqlX5w7qeZsA11BiFJfTD/4aort0YM37eyt5l,iv:0JyLVr/j9YkeTg3Vm+T2Uf0o02APHI+perc+oEiLpfo=,tag:Kx5b/5Vb+J59+ZpBuwMRvQ==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:gxpRyGxvLrrBDjcQGQi46MnRd/CMCN1Jakh5JI2ARIDoSX6hbEB1nBHc2xVG1ukTKUhpKInwhoAEj2EPXLg=,iv:iBrw6T/uC0rOYGMvIBg1xKP055KBfdZFg7fQ04MVVak=,tag:8K0Fp/EgOS2Vk/wmsrjAJA==,type:str]
doco_cd_age_keys:
    misskey-blue: ENC[AES256_GCM,data:Jmzp8DmqZQIw7uQ7TPsMOfjBwMtZFh1Ui0yjSHTr0kzCfLTcwnGQXRiKrjXXeHQ9XFCy5F+VMBlIFF6S9DRxGcwxxwmdozVmAtsvJFTp86QtWjI8BdFPaoftbA5eEH/nawrsNxy04MSCawhy1iBKWHEFpEHX725i5ob/1Bq9mxOPvEFJGQ8+Rt3771HSnIFHvFaz0Bc25pYCWSKjfvqsVKIggBOcAjil4Wdz+dnjJeXOXhX0gbjZf1BvjKQ=,iv:x9043OlQt67wAqeGb/eIvwaoWaUJ6H1gbIvILBqcEfc=,tag:wNuct3OI7TsxihcxSHlFDA==,type:str]
    media-proxy: ENC[AES256_GCM,data:JVKRdT5qrWKOpQsLe5Rqlfrji2CK8mbLGmFh/dm1ohRmKIh6kx/VxCqxBqm5viA3NlV7eRVlQR8/qfMQhNNcsrcaPdYFQ0kt6Y6MadOMiNT5gOVg609loF1lgsL8+spA4HIxdJGTlDlVo83pejJsP05dj8ypt64YeqR1tHOK3K+CFgMyqXNLpH3AckMKjBPG0D1TmEL5Mc5JWrOL7oN9pPxXDMZFmWSlKV3YnicNqarJmL74DOt1QKcJobg=,iv:xEKOr5wjdobQIoIyMIv6EwJLNZ7FAUjqtbRcgjtttA0=,tag:i3VO+/yTJ+DEbhx6oLIKKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UFlCZUxSVjZoaWQ1ZWp5
            azlZOVpRM2pPRS9sMmVBK3ZnenJYTEU1UDNVCjJNWWIrbnZ3cWlFdHBua3BJYzZY
            TVZEcVFVWHlFekMrZkMxekFLZGQ3TFkKLS0tIHVYOElNRjdjNHVHbW4rbnVIRnZm
            eWNZdWpPYlhJTGFIWVJ0RkVHT2doMTQKwv1OTH9GySqj6FpvdFUml+q47LXTjlh4
            D79jkGUgOmghwWUixIbtibwqeTp6DI2qPpHnoo3IGQLAj4NJoaaeGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145yagqxlptxtw0jg3yawdqj6r6075l3svdakhhe6t7u4nfterg7qall256
    lastmodified: "2026-09-17T14:04:42Z"
    mac: ENC[AES256_GCM,data:14FUxMBH9FXO0nITkczYPAlvbAI5dt3FIV2WbuGwGbGPy9dq8TlRIp85quss6gQM0eBdFptOIsgY7nmoPOlpAHFlSpB3xo1o7vf+lZYkzjamEb4HFSHvc6YN0P4oOeDRgGP15IZ32b/nolFLmiPPpkgMsoGSeUe76c3UBHrj7Jo=,iv:HE5f2x7V17wMdD+0TZX0Xmp1tSn7A/JrivW/YTy+jmQ=,tag:+od/PEo62CbtsLQ1LBvPbA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
