doco_cd_age_key: ENC[AES256_GCM,data:7NdEB0B20tDxuLd+Pah1v49XPIgFdg7loToXCjaN2hYv7b7Gp/GPswbU7HMbWuaoTb8YWSyDhin0WRxbQmt+MU0kGw+y8dyUcFCb4NdvB+CUWEAN3z7mMj7VpWWlajV7Vt+pgyVAViMtnkmOFAxh1H0oahRuQhDsdwuAHy5HSF0qZ9NRYI2ugwhWIbcHlg4n6k7OCiPeey+4dF1O2XTw7SQFVWizbbhtDUJqhilKnM0tuK72oeGvUDf8Q3k6,iv:JqfB07GKXB4sURQ38Df0xbR6vzB6pLJQzS+JQMI76uc=,tag:LsEFdlajvV+MvR0Bp5eWng==,type:str]
apprise_notify_urls: ENC[AES256_GCM,data:TMtRMj3u3gbXdd8r0VCWDaGYCWIPjABktctXIJH2s1WmHyXCNFC4pJQ61qDbrYcO+6o8tnZmsHnGzXgqdgrNfqcbAV4vnp9MDSfybBcpwg6c/Pcp3IrhfDJhzKgIEdS8Ce1z,iv:ERWUrmqdtqjyxEC/eMJFtEpGTsgKv1gMlM0LycvTHjE=,tag:hb/lZzeCvKytfVQozg2B7g==,type:str]
admin_user_password_hash: ENC[AES256_GCM,data:oka5W75RmBSevg5QhgnZSScypQWuJWu/MEsoQcCYf51eFyGQpd5UeYz5NjcxfWC4t45/B8LmPdH+866sZ1OiauPk+1afLZxr+s/fU3mkLCBwPnQf5KfSG6iRK9LQqlX5w7qeZsA11BiFJfTD/4aort0YM37eyt5l,iv:0JyLVr/j9YkeTg3Vm+T2Uf0o02APHI+perc+oEiLpfo=,tag:Kx5b/5Vb+J59+ZpBuwMRvQ==,type:str]
tailscale_auth_key: ENC[AES256_GCM,data:eKTfUpkyVgTMwI6NOn6S+hwNb+6rJoM+oP74nhOqckCFy1gvlIA62pySRq4AQYK4g1kgBlnELxms9j81Rw==,iv:2/Ewcq/jTnGZoQcPLhngyHgazxaZGyA/vkXl8adoyHU=,tag:ewFQ+Fp6DJ6i79iFVsCGwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UFlCZUxSVjZoaWQ1ZWp5
            azlZOVpRM2pPRS9sMmVBK3ZnenJYTEU1UDNVCjJNWWIrbnZ3cWlFdHBua3BJYzZY
            TVZEcVFVWHlFekMrZkMxekFLZGQ3TFkKLS0tIHVYOElNRjdjNHVHbW4rbnVIRnZm
            eWNZdWpPYlhJTGFIWVJ0RkVHT2doMTQKwv1OTH9GySqj6FpvdFUml+q47LXTjlh4
            D79jkGUgOmghwWUixIbtibwqeTp6DI2qPpHnoo3IGQLAj4NJoaaeGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age145yagqxlptxtw0jg3yawdqj6r6075l3svdakhhe6t7u4nfterg7qall256
    lastmodified: "2026-09-09T15:50:21Z"
    mac: ENC[AES256_GCM,data:2SQvtQmx7m0XgnC+hEJXjqmK4JL5pJnk+iKDra68StUUdF8vMdWznZuPuKLIfTlGi481BvwRwtlZ2pbFIDar0eH1zJ4xIWe3Dwi+jv372MZ7eczbN9skuQBNTbSd3vzV7MuVfU/F5MsQ94HUAARg/59V0a7O+b2weLJzK7LochA=,iv:A4EOK1XTsu0orEacW11xksJwow1f11on7PX8aNdUGRw=,tag:WWKYmxHkfFU4SYmLQ2Hf5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
