services:
  proxy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../../shared/certificate.pem:/etc/ssl/certs/certificate.pem
      - ../../shared/key.pem:/etc/ssl/private/key.pem
      - caddy-data:/data
      - caddy-config:/config
      - caddy-logs:/var/log/caddy
    networks:
      - internal_network

  media-proxy:
    image: ghcr.io/yojo-art/media-proxy-rs:main@sha256:4559e3cc42a49109f72f48d1418a8aa107a5bd0a9932de9159679ba8be0659f4
    restart: always
    environment:
      MEDIA_PROXY_CONFIG_PATH: /etc/media-proxy/config.json
    volumes:
      - ./config.json:/etc/media-proxy/config.json:ro
    networks:
      - internal_network

networks:
  internal_network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd3c:9a51:7e09::/64

volumes:
  caddy-data:
  caddy-config:
  caddy-logs:
